<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Contracts\" />
    <Folder Include="Features\Candidates\Commands\" />
    <Folder Include="Features\Candidates\" />
    <Folder Include="Features\Candidates\Queries\" />
    <Folder Include="Features\Employers\Commands\" />
    <Folder Include="Features\Employers\Queries\" />
    <Folder Include="Features\Jobs\Commands\" />
    <Folder Include="Features\Jobs\Queries\" />
    <Folder Include="MappingProfiles\" />
    <Folder Include="Behaviors\" />
    <Folder Include="Exceprions\" />
  </ItemGroup>

</Project>
